### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/PY202309-P#1]
1. 기능이 다소 부족해보입니다. 기능을 추가하거나 확장하십시오. (예: 키워드들 중 정말 중요한 애들만 추출하는 것. 예를 들면 "사용자" 라는 단어가 많이 등장하더라도, 문서 도메인에 따라서 실제로는 "사용자"가 중요한 키워드가 아닐 수 있습니다. )
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by haegun2** [comment]
확장 후 진척보고서 반영 완료하여 close 처리 하였습니다~
